CREATE TABLE Items (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(100) NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    Stock INT NOT NULL
);

CREATE TABLE Transactions (
    Id INT PRIMARY KEY IDENTITY(1,1),
    ItemId INT NOT NULL,
    Amount DECIMAL(10, 2) NOT NULL,
    PurchaseDate DATETIME NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (ItemId) REFERENCES Items(Id)
);

CREATE TABLE InventoryChangeLog (
    Id INT PRIMARY KEY IDENTITY(1,1),
    ItemId INT NOT NULL,
    ChangeType NVARCHAR(50) NOT NULL,
    Timestamp DATETIME NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (ItemId) REFERENCES Items(Id)
);